"""
Config Tooltips - Descriptions for all config variables
Extracted from Posterizarr documentation
"""

# Comprehensive tooltip descriptions for all config variables
CONFIG_TOOLTIPS = {
    # WebUI Settings
    "basicAuthEnabled": "Enable Basic Authentication to protect the Web UI. When set to true, the UI requires a username and password for access.",
    "basicAuthUsername": "The username for UI authentication. (Default: admin)",
    "basicAuthPassword": "The password for UI authentication. IMPORTANT: Change this from the default 'posterizarr' before enabling auth! (Default: posterizarr)",

    # ApiPart
    "tvdbapi": "Your TVDB Project API key. If you are a TVDB subscriber, you can append your PIN to the end of your API key in the format YourApiKey#YourPin. It is important to include a # between the API key and the PIN.",
    "tmdbtoken": "Your TMDB API Read Access Token (the really long one).",
    "FanartTvAPIKey": "Your Fanart personal API key.",
    "PlexToken": "Your Plex token (Leave empty if not applicable).",
    "JellyfinAPIKey": "Your Jellyfin API key. You can create an API key from inside Jellyfin at Settings > Advanced > Api Keys.",
    "EmbyAPIKey": "Your Emby API key. You can create an API key from inside Emby at Settings > Advanced > Api Keys.",
    "FavProvider": "Set your preferred provider (default is tmdb). Possible values are tmdb (recommended), fanart, tvdb, or plex (not recommended). Plex should act as a last resort, especially if you prefer textless artwork, as it cannot be queried for text.",
    "tmdb_vote_sorting": "Picture sorting via TMDB api, either by vote_average, vote_count or by primary (default tmdb view like on the website). Default is vote_average.",
    "PreferredLanguageOrder": "Specify language preferences. Default is xx,en,de (xx is Textless). Use 2-digit ISO 3166-1 language codes. If you set it to xx you tell the script it should only search for textless, posters with text will be skipped.",
    "PreferredSeasonLanguageOrder": "Specify language preferences for seasons. Default is xx,en,de (xx is Textless). Use 2-digit ISO 3166-1 language codes.",
    "PreferredBackgroundLanguageOrder": "Specify language preferences for backgrounds. Default is PleaseFillMe (It will take your poster lang order / xx is Textless). If you set it to xx you tell the script it should only search for textless, posters with text will be skipped.",
    "PreferredTCLanguageOrder": "Specify language preferences for TCs. Default is PleaseFillMe (It will take your poster lang order / xx is Textless). If you set it to xx you tell the script it should only search for textless, posters with text will be skipped.",
    "WidthHeightFilter": "If set to true, an additional resolution filter will be applied to Posters/Backgrounds (TMDB and TVDB) and Titlecards (only on TMDB) searches.",
    "PosterMinWidth": "Minimum poster width filter—greater than or equal to: 2000 (default value).",
    "PosterMinHeight": "Minimum poster height filter—greater than or equal to: 3000 (default value).",
    "BgTcMinWidth": "Minimum background/titlecard width filter—greater than or equal to: 3840 (default value).",
    "BgTcMinHeight": "Minimum background/titlecard height filter—greater than or equal to: 2160 (default value).",
    "LogoLanguageOrder": "Specify language preferences for Logos. Default is en,de. Use 2-digit ISO 3166-1 language codes.",

    # PlexPart
    "PlexLibstoExclude": "Libraries, by name, to exclude from processing on your Plex server.",
    "PlexUrl": "Plex server URL (i.e. 'http://192.168.1.1:32400' or 'http://myplexserver.com:32400').",
    "UsePlex": "If set to true, you tell the script to use a Plex Server (Default value is: true). Do not enable more than one media server.",
    "PlexUploadExistingAssets": "If set to true, the script will check local assets and upload them to Plex, but only if Plex does not already have EXIF data from Posterizarr, Kometa, or TCM for the artwork being uploaded.",
    "PlexUpload": "If set to true, Posterizarr will directly upload the artwork to Plex (handy if you do not use Kometa).",

    # JellyfinPart
    "JellyfinLibstoExclude": "Libraries, by local folder name, to exclude from processing on your Jellyfin server.",
    "JellyfinUrl": "Jellyfin server URL (i.e. 'http://192.168.1.1:8096' or 'http://myplexserver.com:8096').",
    "UseJellyfin": "If set to true, you tell the script to use a Jellyfin Server (Default value is: false). Do not enable more than one media server.",
    "JellyfinUploadExistingAssets": "If set to true, the script will check local assets and upload them to Jellyfin, but only if Jellyfin does not already have EXIF data from Posterizarr, Kometa, or TCM for the artwork being uploaded.",
    "JellyfinReplaceThumbwithBackdrop": "If set to true (Default value is: false), the script will replace the Thumb picture with the backdrop image. This will only occur if BackgroundPosters is also set to true.",

    # EmbyPart
    "EmbyLibstoExclude": "Libraries, by local folder name, to exclude from processing on your Emby server.",
    "EmbyUrl": "Emby server URL (i.e. 'http://192.168.1.1:8096/emby' or 'http://myplexserver.com:8096/emby').",
    "UseEmby": "If set to true, you tell the script to use a Emby Server (Default value is: false). Do not enable more than one media server.",
    "EmbyUploadExistingAssets": "If set to true, the script will check local assets and upload them to Emby, but only if Emby does not already have EXIF data from Posterizarr, Kometa, or TCM for the artwork being uploaded.",
    "EmbyReplaceThumbwithBackdrop": "If set to true (Default value is: false), the script will replace the Thumb picture with the backdrop image. This will only occur if BackgroundPosters is also set to true.",

    # Notification
    "SendNotification": "Set to true if you want to send notifications via discord or apprise, else false.",
    "AppriseUrl": "Only possible on Docker - Url for apprise provider. See Apprise documentation for details.",
    "Discord": "Discord Webhook Url for notifications.",
    "DiscordUserName": "Username for the discord webhook, default is Posterizarr.",
    "UseUptimeKuma": "Set to true if you want to send webhook to Uptime-Kuma.",
    "UptimeKumaUrl": "Uptime-Kuma Webhook Url.",

    # PrerequisitePart
    "AssetPath": "Path to store generated posters. On Docker, this should be /assets.",
    "FileTestOnTrigger": "On trigger run, checks whether the file is present locally. If set to false, the test will be skipped and all images will be overwritten.",
    "BackupPath": "Path to store/download Plex posters when using the backup switch.",
    "ManualAssetPath": "If assets are placed in this directory with the exact naming convention, they will be preferred. It has to follow the same naming convention as you have in /assets.",
    "SkipAddText": "If set to true, Posterizarr will skip adding text/logo to the poster if it is flagged as a Poster with text by the provider.",
    "SkipLocalPosterTextAdd": "If set to true, Posterizarr will skip adding text to the local poster.",
    "SkipLocalBackgroundTextAdd": "If set to true, Posterizarr will skip adding text to the local background poster.",
    "SkipLocalSeasonTextAdd": "If set to true, Posterizarr will skip adding text to the local season poster.",
    "SkipLocalTCTextAdd": "If set to true, Posterizarr will skip adding text to the local TC.",
    "SkipAddTextAndOverlay": "If set to true, Posterizarr will skip adding text/overlay to the poster if it is flagged as a Poster with text by the provider.",
    "SkipAddTextAndBorder": "If set to true, Posterizarr will skip adding text/border to the poster if it is flagged as a Poster with text by the provider.",
    "FollowSymlink": "If set to true, Posterizarr will follow symbolic links in the specified directories during hashtable creation, allowing it to process files and folders pointed to by the symlinks. This is useful if your assets are organized with symlinks instead of duplicating files.",
    "ForceRunningDeletion": "If set to true, Posterizarr will automatically delete the Running File. Warning: This may result in multiple concurrent runs sharing the same temporary directory, potentially causing image artifacts or unexpected behavior during processing.",
    "AutoUpdatePosterizarr": "If set to true, Posterizarr will update itself to latest version. (Only for non docker systems).",
    "show_skipped": "If set to true, verbose logging of already created assets will be displayed; otherwise, they will be silently skipped - On large libraries, this may appear as if the script is hanging.",
    "magickinstalllocation": "The path to the ImageMagick installation where magick.exe is located. If you prefer using a portable version, leave the value as './magick'. The container manages this automatically, so you can leave the default value in the configuration.",
    "maxLogs": "Number of Log folders you want to keep in RotatedLogs Folder (Log History).",
    "logLevel": "Sets the verbosity of logging. 1 logs Warning/Error messages. Default is 2 which logs Info/Warning/Error messages. 3 captures Info/Warning/Error/Debug messages and is the most verbose.",
    "font": "Font file name.",
    "RTLFont": "RTL Font file name.",
    "backgroundfont": "Background font file name.",
    "titlecardfont": "Font file name for title card text.",
    "collectionfont": "Font file name for collection titles.",
    "overlayfile": "Overlay file name.",
    "showoverlayfile": "Overlay file name.",
    "seasonoverlayfile": "Season overlay file name.",
    "backgroundoverlayfile": "Background overlay file name.",
    "showbackgroundoverlayfile": "Background overlay file name.",
    "titlecardoverlayfile": "Title Card overlay file name.",
    "collectionoverlayfile": "Collection overlay file name.",
    "poster4k": "4K Poster overlay file name. (overlay has to match the Poster dimensions 2000x3000).",
    "Poster1080p": "1080p Poster overlay file name. (overlay has to match the Poster dimensions 2000x3000).",
    "Background4k": "4K Background overlay file name. (overlay has to match the Background dimensions 3840x2160).",
    "Background1080p": "1080p Background overlay file name. (overlay has to match the Background dimensions 3840x2160).",
    "TC4k": "4K TitleCard overlay file name. (overlay has to match the Poster dimensions 3840x2160).",
    "TC1080p": "1080p TitleCard overlay file name. (overlay has to match the Poster dimensions 3840x2160).",
    "UsePosterResolutionOverlays": "Set to true to apply specific overlay with resolution for 4k/1080p posters. If you only want 4k just add your default overlay file also for Poster1080p.",
    "UseBackgroundResolutionOverlays": "Set to true to apply specific overlay with resolution for 4k/1080p posters. If you only want 4k just add your default overlay file also for Background1080p.",
    "UseTCResolutionOverlays": "Set to true to apply specific overlay with resolution for 4k/1080p posters. If you only want 4k - add your default (without a resolution) overlay file for TC1080p.",
    "LibraryFolders": "Set to false for asset structure in one flat folder or true to split into library media folders like Kometa needs it.",
    "Posters": "Set to true to create movie/show posters.",
    "SeasonPosters": "Set to true to also create season posters.",
    "BackgroundPosters": "Set to true to also create background posters.",
    "TitleCards": "Set to true to also create title cards.",
    "SkipTBA": "If set to true, TitleCard creation will be skipped when TitleText contains any word from SkipWords.",
    "SkipWords": "List of words to be skipped for TC, e.g 'TBA, Episode...'. Any already created TitleCards that match these words will be deleted.",
    "SkipJapTitle": "Set to true to skip TitleCard creation if the Titletext is Jap or Chinese.",
    "AssetCleanup": "Set to true to cleanup Assets that are no longer in Plex. Warning: Risk of Data Loss from excluded Libraries. Ensure that all active asset libraries are included when using that setting on true to prevent unintended deletions.",
    "AutoUpdateIM": "Set to true to AutoUpdate Imagemagick Portable Version (Does not work with Docker/Unraid). Doing this could break things, cause you then use IM Versions that are not tested with Posterizarr.",
    "NewLineOnSpecificSymbols": "Set to true to enable automatic insertion of a newline character at each occurrence of specific symbols in NewLineSymbols within the title text.",
    "NewLineSymbols": "A list of symbols that will trigger a newline insertion when NewLineOnSpecificSymbols is set to true. Separate each symbol with a comma (e.g., ' - ', ':').",
    "SymbolsToKeepOnNewLine": "A list of symbols that trigger a newline insertion but are not replaced by the newline character. This only applies if the symbol is also included in NewLineSymbols. Separate each symbol with a comma (e.g., '-', ':').",
    "NewLineOnSpecificWords": "Set to true to enable the automatic replacement of specific words with formatted versions (such as hyphenated breaks) as defined in NewLineWords.",
    "NewLineWords": "A mapping of specific words to their desired replacement format. Each entry consists of a 'Key': 'Value' pair (e.g., 'FEUERZANGENBOWLE': 'FEUERZANGEN-\\nBOWLE'). This is used to manually force newlines or hyphens into long words for better visual layout.",
    "DisableHashValidation": "Set to true to skip hash validation (Default value is: false). Note: This may produce bloat, as every item will be re-uploaded to the media servers.",
    "DisableOnlineAssetFetch": "Set to true to skip all online lookups and use only locally available assets. (Default value is: false).",
    "UseLogo": "Set to true to apply logos instead of title text to Posters.",
    "UseBGLogo": "Set to true to apply logos instead of title text to Backgrounds.",
    "UseClearlogo": "Set to true to use Clearlogo. A Clearlogo is a transparent PNG image that contains only the title text (logo) of a movie or show - no characters, no background, no extra artwork.",
    "UseClearart": "Set to true to use Clearart. Clearart is a transparent PNG image that contains the logo plus additional artwork (e.g., characters or promotional art) - still fully transparent with no background.",
    "LogoTextFallback": "Set to true to fallback to Text if no logos are found.",
    "ConvertLogoColor": "Set to true to convert the logo image to a solid color (monochrome).",
    "LogoFlatColor": "The specific color to use when Convert Logo Color is enabled (e.g., 'white', '#FFFFFF').",
    "UseOriginalTitle": "Set to true to use the original title instead of the localized version.",
    "telemetry": "Set to true to participate in anonymous telemetry that helps the developers understand global usage (sends instance ID, OS, Target, and Country).",

    # OverlayPart
    "ImageProcessing": "Set to true if you want the ImageMagick part (text, overlay and/or border); if false, it only downloads the posters.",
    "outputQuality": "Image output quality, default is 92% if you set it to 100% the image size gets doubled.",

    # PosterOverlayPart
    "PosterFontAllCaps": "Set to true for all caps text on posters, else false.",
    "PosterAddBorder": "Set to true to add a border to the poster image.",
    "PosterAddText": "Set to true to add text/logo to the poster image.",
    "PosterAddOverlay": "Set to true to add the defined overlay file to the poster image.",
    "PosterFontcolor": "Color of font text on posters (e.g., #FFFFFF for white).",
    "PosterBordercolor": "Color of border on posters (e.g., #000000 for black).",
    "PosterMinPointSize": "Minimum size of text in poster (in points).",
    "PosterMaxPointSize": "Maximum size of text in poster (in points).",
    "PosterBorderwidth": "Border width in pixels.",
    "PosterMaxWidth": "Maximum width of text box on poster.",
    "PosterMaxHeight": "Maximum height of text box on poster.",
    "PosterTextOffset": "Text box offset from the bottom of the picture (use +200 or -150 format).",
    "PosterAddTextStroke": "Set to true to add stroke/outline to text.",
    "PosterStrokecolor": "Color of text stroke/outline (e.g., #000000 for black).",
    "PosterStrokewidth": "Stroke width in pixels.",
    "PosterLineSpacing": "Adjust the height between lines of text (Default is 0).",
    "PosterTextGravity": "Specifies the text alignment within the textbox (Default is south = bottom center).",

    # SeasonPosterOverlayPart
    "SeasonPosterFontAllCaps": "Set to true for all caps text on season posters, else false.",
    "SeasonPosterOverrideSeasonName": "Set to true to override the default season poster title with a custom name.",
    "SeasonPosterSeasonOverrideText": "The custom default text to use for regular seasons when Override Season Name is enabled.",
    "SeasonPosterSpecialSeasonOverrideText": "The custom default text to use for Special seasons (Season 00) when Override Season Name is enabled.",
    "SeasonPosterAddBorder": "Set to true to add a border to the season poster image.",
    "SeasonPosterAddText": "Set to true to add text to the season poster image.",
    "SeasonPosterAddOverlay": "Set to true to add the defined overlay file to the season poster image.",
    "SeasonPosterFontcolor": "Color of font text on season posters.",
    "SeasonPosterBordercolor": "Color of border on season posters.",
    "SeasonPosterMinPointSize": "Minimum size of text in season poster.",
    "SeasonPosterMaxPointSize": "Maximum size of text in season poster.",
    "SeasonPosterBorderwidth": "Border width in pixels for season posters.",
    "SeasonPosterMaxWidth": "Maximum width of text box on season poster.",
    "SeasonPosterMaxHeight": "Maximum height of text box on season poster.",
    "SeasonPosterTextOffset": "Text box offset from the bottom of the season poster (use +200 or -150 format).",
    "SeasonPosterAddTextStroke": "Set to true to add stroke/outline to text on season posters.",
    "SeasonPosterStrokecolor": "Color of text stroke/outline on season posters.",
    "SeasonPosterStrokewidth": "Stroke width in pixels for season posters.",
    "SeasonPosterLineSpacing": "Adjust the height between lines of text on season posters (Default is 0).",
    "SeasonPosterShowFallback": "Set to true if you want to fallback to show poster if no season poster was found.",
    "SeasonPosterTextGravity": "Specifies the text alignment within the textbox on season posters (Default is south).",

    # BackgroundOverlayPart
    "BackgroundFontAllCaps": "Set to true for all caps text on backgrounds, else false.",
    "BackgroundAddOverlay": "Set to true to add the defined background overlay file to the background image.",
    "BackgroundAddBorder": "Set to true to add a border to the background image.",
    "BackgroundAddText": "Set to true to add text/logo to the background image.",
    "BackgroundFontcolor": "Color of font text on backgrounds.",
    "BackgroundBordercolor": "Color of border on backgrounds.",
    "BackgroundMinPointSize": "Minimum size of text in background image.",
    "BackgroundMaxPointSize": "Maximum size of text in background image.",
    "BackgroundBorderwidth": "Border width in pixels for backgrounds.",
    "BackgroundMaxWidth": "Maximum width of text box in background image.",
    "BackgroundMaxHeight": "Maximum height of text box in background image.",
    "BackgroundTextOffset": "Text box offset from the bottom of the background image (use +200 or -150 format).",
    "BackgroundAddTextStroke": "Set to true to add stroke/outline to text on backgrounds.",
    "BackgroundStrokecolor": "Color of text stroke/outline on backgrounds.",
    "BackgroundStrokewidth": "Stroke width in pixels for backgrounds.",
    "BackgroundLineSpacing": "Adjust the height between lines of text on backgrounds (Default is 0).",
    "BackgroundTextGravity": "Specifies the text alignment within the textbox on backgrounds (Default is south).",

    # TitleCardOverlayPart
    "TitleCardUseBackgroundAsTitleCard": "Set to true if you prefer show background as TitleCard, default is false where it uses episode image as TitleCard.",
    "TitleCardAddOverlay": "Set to true to add the defined TitleCard overlay file to the TitleCard image.",
    "TitleCardAddBorder": "Set to true to add a border to the TitleCard image.",
    "TitleCardBordercolor": "Color of border on title cards.",
    "TitleCardBorderwidth": "Border width in pixels for title cards.",
    "TitleCardBackgroundFallback": "Set to false if you want to skip Background fallback for TitleCard images if no TitleCard was found.",

    # TitleCardTitleTextPart
    "TitleCardTitleFontAllCaps": "Set to true for all caps episode title text on title cards, else false.",
    "TitleCardTitleAddEPTitleText": "Set to true to add episode title text to the TitleCard image.",
    "TitleCardTitleFontcolor": "Color of episode title font text on title cards.",
    "TitleCardTitleMinPointSize": "Minimum size of episode title text in TitleCard image.",
    "TitleCardTitleMaxPointSize": "Maximum size of episode title text in TitleCard image.",
    "TitleCardTitleMaxWidth": "Maximum width of episode title text box in TitleCard image.",
    "TitleCardTitleMaxHeight": "Maximum height of episode title text box in TitleCard image.",
    "TitleCardTitleTextOffset": "Episode title text box offset from the bottom of the TitleCard image (use +200 or -150 format).",
    "TitleCardTitleAddTextStroke": "Set to true to add stroke/outline to episode title text on title cards.",
    "TitleCardTitleStrokecolor": "Color of episode title text stroke/outline on title cards.",
    "TitleCardTitleStrokewidth": "Stroke width in pixels for episode title text on title cards.",
    "TitleCardTitleLineSpacing": "Adjust the height between lines of episode title text on title cards (Default is 0).",
    "TitleCardTitleTextGravity": "Specifies the episode title text alignment within the textbox on title cards (Default is south).",

    # TitleCardEPTextPart
    "TitleCardEPSeasonTCText": "You can Specify the default text for 'Season' that appears on TitleCard. Example: 'STAFFEL 1 • EPISODE 5' or 'SÄSONG 1 • EPISODE 1'.",
    "TitleCardEPEpisodeTCText": "You can Specify the default text for 'Episode' that appears on TitleCard. Example: 'SEASON 1 • EPISODE 5' or 'SEASON 1 • AVSNITT 1'.",
    "TitleCardEPFontAllCaps": "Set to true for all caps episode number text on title cards, else false.",
    "TitleCardEPAddEPText": "Set to true to add episode number text (Season X • Episode Y) to the TitleCard image.",
    "TitleCardEPFontcolor": "Color of episode number font text on title cards.",
    "TitleCardEPMinPointSize": "Minimum size of episode number text in TitleCard image.",
    "TitleCardEPMaxPointSize": "Maximum size of episode number text in TitleCard image.",
    "TitleCardEPMaxWidth": "Maximum width of episode number text box in TitleCard image.",
    "TitleCardEPMaxHeight": "Maximum height of episode number text box in TitleCard image.",
    "TitleCardEPTextOffset": "Episode number text box offset from the bottom of the TitleCard image (use +200 or -150 format).",
    "TitleCardEPAddTextStroke": "Set to true to add stroke/outline to episode number text on title cards.",
    "TitleCardEPStrokecolor": "Color of episode number text stroke/outline on title cards.",
    "TitleCardEPStrokewidth": "Stroke width in pixels for episode number text on title cards.",
    "TitleCardEPLineSpacing": "Adjust the height between lines of episode number text on title cards (Default is 0).",
    "TitleCardEPTextGravity": "Specifies the episode number text alignment within the textbox on title cards (Default is south).",

    # ShowTitleOnSeasonPosterPart
    "ShowTitleAddShowTitletoSeason": "If set to true it will add show title/logo to season poster (Default Value is: false).",
    "ShowTitleFontAllCaps": "Set to true for all caps show title text on season posters, else false.",
    "ShowTitleAddTextStroke": "Set to true to add stroke/outline to show title text on season posters.",
    "ShowTitleStrokecolor": "Color of show title text stroke/outline on season posters.",
    "ShowTitleStrokewidth": "Stroke width in pixels for show title text on season posters.",
    "ShowTitleFontcolor": "Color of show title font text on season posters.",
    "ShowTitleMinPointSize": "Minimum size of show title text on season posters.",
    "ShowTitleMaxPointSize": "Maximum size of show title text on season posters.",
    "ShowTitleMaxWidth": "Maximum width of show title text box on season posters.",
    "ShowTitleMaxHeight": "Maximum height of show title text box on season posters.",
    "ShowTitleTextOffset": "Show title text box offset from the bottom of the season poster (use +200 or -150 format).",
    "ShowTitleLineSpacing": "Adjust the height between lines of show title text on season posters (Default is 0).",
    "ShowTitleTextGravity": "Specifies the show title text alignment within the textbox on season posters (Default is south).",

    # CollectionTitlePosterPart
    "CollectionTitleAddCollectionTitle": "If set to true it will add collectiontitle to collection poster (Default Value is: true).",
    "CollectionTitleCollectionTitle": "Extra text that gets added to the collection poster (Default is 'Collection').",
    "CollectionTitleFontAllCaps": "Set to true for all caps collection title text, else false.",
    "CollectionTitleAddTextStroke": "Set to true to add stroke/outline to collection title text.",
    "CollectionTitleStrokecolor": "Color of collection title text stroke/outline.",
    "CollectionTitleStrokewidth": "Stroke width in pixels for collection title text.",
    "CollectionTitleFontcolor": "Color of collection title font text.",
    "CollectionTitleMinPointSize": "Minimum size of collection title text.",
    "CollectionTitleMaxPointSize": "Maximum size of collection title text.",
    "CollectionTitleMaxWidth": "Maximum width of collection title text box.",
    "CollectionTitleMaxHeight": "Maximum height of collection title text box.",
    "CollectionTitleTextOffset": "Collection title text box offset from the bottom of the poster (use +200 or -150 format).",
    "CollectionTitleLineSpacing": "Adjust the height between lines of collection title text (Default is 0).",
    "CollectionTitleTextGravity": "Specifies the collection title text alignment within the textbox (Default is south).",

    # CollectionPosterOverlayPart
    "CollectionPosterFontAllCaps": "Set to true for all caps text on collection posters, else false.",
    "CollectionPosterAddBorder": "Set to true to add a border to the collection poster image.",
    "CollectionPosterAddText": "Set to true to add text to the collection poster image.",
    "CollectionPosterAddTextStroke": "Set to true to add stroke/outline to text on collection posters.",
    "CollectionPosterStrokecolor": "Color of text stroke/outline on collection posters.",
    "CollectionPosterStrokewidth": "Stroke width in pixels for collection posters.",
    "CollectionPosterAddOverlay": "Set to true to add the defined overlay file to the collection poster image.",
    "CollectionPosterFontcolor": "Color of font text on collection posters.",
    "CollectionPosterBordercolor": "Color of border on collection posters.",
    "CollectionPosterMinPointSize": "Minimum size of text in collection poster.",
    "CollectionPosterMaxPointSize": "Maximum size of text in collection poster.",
    "CollectionPosterBorderwidth": "Border width in pixels for collection posters.",
    "CollectionPosterMaxWidth": "Maximum width of text box on collection poster.",
    "CollectionPosterMaxHeight": "Maximum height of text box on collection poster.",
    "CollectionPosterTextOffset": "Text box offset from the bottom of the collection poster (use +200 or -150 format).",
    "CollectionPosterLineSpacing": "Adjust the height between lines of text on collection posters (Default is 0).",
    "CollectionPosterTextGravity": "Specifies the text alignment within the textbox on collection posters (Default is south).",
}

def get_tooltip(key):
    """Get tooltip description for a config key"""
    return CONFIG_TOOLTIPS.get(key, "")